# nixpacks.toml (Версия 4 - Легкая, с внешним браузером)

[phases.setup]
# Шаг 1: Устанавливаем ТОЛЬКО Node.js. Никакого Chromium.
nixPkgs = ["nodejs_20"]

[phases.install]
# Шаг 2: Устанавливаем зависимости из package.json
cmds = ["npm install --production"]

[start]
# Принудительно устанавливаем порт n8n из переменной Railway перед запуском
cmd = "export N8N_PORT=$PORT && n8n"

