# nixpacks.toml (Версия 4 - Легкая, с внешним браузером)

[phases.setup]
# Шаг 1: Устанавливаем ТОЛЬКО Node.js. Никакого Chromium.
nixPkgs = ["nodejs_20"]

[phases.install]
# Шаг 2: Устанавливаем зависимости из package.json
cmds = ["npm install --production"]

[start]
# Шаг 3: Запускаем n8n
cmd = "n8n"
